import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import {NuqsAdapter} from "nuqs/adapters/next/app";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-50 text-foreground`}
      >
        <div className="p-4">
          <NuqsAdapter>
            <header className="mb-4">
              <h1 className="text-2xl font-bold">
                DataTable: Consumindo Dados do Servidor (Consuming Data from
                Server)
              </h1>
            </header>
            <main>{children}</main>
          </NuqsAdapter>
        </div>
      </body>
    </html>
  );
}
